# server.port=80
# server.servlet.context-path=/boot

# yaml有层次，可以继承的配置文件格式
# key:
# 缩进key： -> key.key
server:
  port: 80
  servlet:
    context-path: /boot


hck:
  user:
    gfs:
      - A
      - B
      - C

#hck:
#  info:
#    name: 黄辰凯 # key:空格值
#    age: 19
#  user:
#    username: root
#    password: 123456
#    gfs:
#      - A
#      - B
#      - C

spring:
  profiles:
    active: test,dev # 激活外部的配置 application-test | application-dev
                     # 外部配置的key和application key重复 外部的覆盖内部！！
                     # jar --active=test

